apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: no7whhgmq-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: no7whhgmq-go 
  name: no7whhgmq-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: no7whhgmq-go 
